import { Review } from '../types';

const reviews : Review[] = [
    {
        id: 0,
        propertyId: 8,
        name: 'Danielle',
        rating: 5,
        description: '',
        date: '',
    },
    {
        id: 1,
        propertyId: 5,
        name: 'Janae',
        rating: 4,
        description: '',
        date: '',
    },
    {
        id: 2,
        propertyId: 7,
        name: 'Eric',
        rating: 5,
        description: '',
        date: '',
    },
    {
        id: 3,
        propertyId: 8,
        name: 'Andrea',
        rating: 3,
        description: '',
        date: '',
    },
    {
        id: 4,
        propertyId: 10,
        name: 'Sonny',
        rating: 5,
        description: '',
        date: '',
    },
    {
        id: 5,
        propertyId: 4,
        name: 'Laila',
        rating: 4,
        description: '',
        date: '',
    },
    {
        id: 6,
        propertyId: 4,
        name: 'Harry',
        rating: 3,
        description: '',
        date: '',
    },
    {
        id: 7,
        propertyId: 11,
        name: 'Tara',
        rating: 3,
        description: '',
        date: '',
    },
    {
        id: 8,
        propertyId: 5,
        name: 'Michelle',
        rating: 5,
        description: '',
        date: '',
    },
    {
        id: 9,
        propertyId: 11,
        name: 'Mitch',
        rating: 4,
        description: '',
        date: '',
    },
    {
        id: 10,
        propertyId: 12,
        name: 'Rachel',
        rating: 5,
        description: '',
        date: '',
    },
    {
        id: 11,
        propertyId: 6,
        name: 'Jameson',
        rating: 4,
        description: '',
        date: '',
    },
    {
        id: 12,
        propertyId: 9,
        name: 'Victoria',
        rating: 5,
        description: '',
        date: '',
    },
    {
        id: 13,
        propertyId: 16,
        name: 'Jamie',
        rating: 3,
        description: '',
        date: '',
    },
    {
        id: 14,
        propertyId: 3,
        name: 'Chandler',
        rating: 5,
        description: '',
        date: '',
    },
    {
        id: 15,
        propertyId: 0,
        name: 'Madison',
        rating: 4,
        description: '',
        date: '',
    },
    {
        id: 16,
        propertyId: 1,
        name: 'Ty',
        rating: 4,
        description: '',
        date: '',
    },
    {
        id: 17,
        propertyId: 2,
        name: 'Jarrett',
        rating: 5,
        description: '',
        date: '',
    },
    {
        id: 18,
        propertyId: 15,
        name: 'Joyce',
        rating: 5,
        description: '',
        date: '',
    },
    {
        id: 19,
        propertyId: 14,
        name: 'Rhett',
        rating: 5,
        description: '',
        date: '',
    },
    {
        id: 20,
        propertyId: 13,
        name: 'Jeremiah',
        rating: 4,
        description: '',
        date: '',
    },
    {
        id: 21,
        propertyId: 15,
        name: 'Dillon',
        rating: 5,
        description: '',
        date: '',
    },
    {
        id: 22,
        propertyId: 2,
        name: 'Mariah',
        rating: 3,
        description: '',
        date: '',
    },
    {
        id: 23,
        propertyId: 3,
        name: 'Kevin',
        rating: 3,
        description: '',
        date: '',
    },
    {
        id: 24,
        propertyId: 6,
        name: 'Alan',
        rating: 5,
        description: '',
        date: '',
    },
    {
        id: 25,
        propertyId: 4,
        name: 'Tim',
        rating: 5,
        description: '',
        date: '',
    },
    {
        id: 26,
        propertyId: 11,
        name: 'Piper',
        rating: 5,
        description: '',
        date: '',
    },
    {
        id: 27,
        propertyId: 9,
        name: 'Jennifer',
        rating: 5,
        description: '',
        date: '',
    },
    {
        id: 28,
        propertyId: 14,
        name: 'John',
        rating: 3,
        description: '',
        date: '',
    },
    {
        id: 29,
        propertyId: 12,
        name: 'Jessica',
        rating: 5,
        description: '',
        date: '',
    },
]

export default reviews;